### ISSUE TITLE
Feedback for “Radial Menu”

### ISSUE THREAD

**Issue by ckc1010** [shinjiesk/plasticity-unofficial-document#12]
Would it be possible to enable a key plus a mouse button for the radial menu shortcuts. Alias had a very elegant solution that used the ctrl + shift key and one of the three mouse buttons to bring up radial menus.  This was incredibly fast as your left pinky is always hovering over the ctrl or shift key. Hold down ctrl shift, plus mouse button one, two or three and swipe in the direction of the command then release the mouse button. It becomes second nature in no time and you barely even see the menu come up.  Three menus ( or more depending on how many mouse buttons you have ) always directly accessible without changing your hand positions at all.

Thanks

Chris

**Comment by shinjiesk** [comment]
Thank you for the feedback. The idea of invoking the radial menu with modifier keys and mouse buttons is good. I'll pass it on to the development team.

**Comment by ckc1010** [comment]
Thanks, I was a 3D modeler at Disney for 8 Years, and we used Alias for a lot of creature modeling at the time. All the modelers there used the crtl + Shift and 3 mouse buttons for their radial shortcuts. It allowed us to have an uncluttered viewport and instant access to all our most used functions. You can fit just about everything you need in 3 radial menus.

Thanks

Chris

________________________________
