### ISSUE TITLE
Question, advice

### ISSUE THREAD

**Issue by FilipeF12** [shinjiesk/plasticity-unofficial-document#13]
Is there an offline manual?
Exporting a cube with holes bool'd from a pair of cylinders... obj looks good in blender, but not daz3d - normals whacked
ty

![plast](https://github.com/shinjiesk/plasticity-unofficial-document/assets/86638612/2bad0144-082e-4937-8217-340368e66a1e)
![blendr](https://github.com/shinjiesk/plasticity-unofficial-document/assets/86638612/646036d0-011e-4f17-b354-e433a8d3675b)
![daz3d](https://github.com/shinjiesk/plasticity-unofficial-document/assets/86638612/eaff1466-fa5b-43f7-bbaf-11880814bb4c)
![dazRender](https://github.com/shinjiesk/plasticity-unofficial-document/assets/86638612/d60927b6-e5bc-4e86-9fa0-32ce73923dfd)

**Comment by shinjiesk** [comment]
We apologize, but we do not have an offline manual available. Regarding daz3d, we do not have information about it.

**Comment by FilipeF12** [comment]
> We apologize, but we do not have an offline manual available. Regarding daz3d, we do not have information about it.

hello. as 'cad for artists' which art programs do you support for materials and rendering?
