### ISSUE TITLE
How to mark dimensions

### ISSUE THREAD

**Issue by DBaoge** [shinjiesk/plasticity-unofficial-document#14]
Hi sir, Please tell me How to mark dimensions. And Dimensions displayed when creating model Font color How to change.

Thanks!

**Comment by shinjiesk** [comment]
I apologize for the delayed response.
We currently provide support for Plasticity on our official Discord. We apologize for the inconvenience. Could you please direct your questions to the Discord help channel?

**For Everyone Including Trial Users**
The Discord for everyone, including trial users, can be accessed at the link below.
https://discord.gg/b6fwenZjez

**For Indie or Studio Users**
The link to the Discord for Indie or Studio users can be found in the purchase confirmation email.

Thank you for your understanding and cooperation.
