### ISSUE TITLE
Feedback for “What's New in version 1.3”

### ISSUE THREAD

**Issue by Owiilnice** [shinjiesk/plasticity-unofficial-document#15]
Hopefully the author will update Chinese version

**Comment by shinjiesk** [comment]
我们接受功能请求。您能在这里提交您的请求吗？
https://plasticity.canny.io/feature-requests

Also, we currently provide support for Plasticity on our official Discord in English. We apologize for the inconvenience. Could you please direct your questions to the Discord help channel?

**For Everyone Including Trial Users**
The Discord for everyone, including trial users, can be accessed at the link below.
https://discord.gg/b6fwenZjez

**For Indie or Studio Users**
The link to the Discord for Indie or Studio users can be found in the purchase confirmation email.

Thank you for your understanding and cooperation.
