### ISSUE TITLE
Feedback for “Download and Installation”

### ISSUE THREAD

**Issue by crazyghost51** [shinjiesk/plasticity-unofficial-document#16]
Good afternoon, I have a problem. I download the program installer, run it, and then the program installs quietly without any icons. When I try to start the application, it starts (I can see the task in the manager), but in reality there is nothing. How to solve this problem?

**Comment by shinjiesk** [comment]
I apologize for the delayed response.
We currently provide support for Plasticity on our official Discord. We apologize for the inconvenience. Could you please direct your questions to the Discord help channel?

**For Everyone Including Trial Users**
The Discord for everyone, including trial users, can be accessed at the link below.
https://discord.gg/b6fwenZjez

**For Indie or Studio Users**
The link to the Discord for Indie or Studio users can be found in the purchase confirmation email.

Thank you for your understanding and cooperation.
