### ISSUE TITLE
How to reopen a closed issue

### ISSUE THREAD

**Issue by FilipeF12** [shinjiesk/plasticity-unofficial-document#17]
My issue #13 was closed. How do I re-open it? I asked a followup question there.

**Comment by shinjiesk** [comment]
I apologize for the delayed response.
We currently provide support for Plasticity on Discord. We apologize for the inconvenience, but could you please ask your questions there?

For Everyone Including Trial Users
The Discord for everyone, including trial users, can be accessed at the link below.
https://discord.gg/b6fwenZjez

For Indie or Studio Users
The link to the Discord for Indie or Studio users can be found in the purchase confirmation email.

Thank you for your understanding and cooperation.
