### ISSUE TITLE
Feedback for “Focus and Isolate Objects”

### ISSUE THREAD

**Issue by luminahox** [shinjiesk/plasticity-unofficial-document#21]
I'm unable to change the shortcut for Isolating selection. I would like to have the . key to focus on objects and the / key to isolate the selection, to match better Blender's shortcuts. I'm able to assign the . key to the focus command, but when I assign the / key to the isolate command, it doesn't work and it still just execute the focus command.

**Comment by shinjiesk** [comment]
We currently provide support for Plasticity on our official Discord. We apologize for the inconvenience. Could you please direct your questions to the Discord help channel?

**For Everyone Including Trial Users**
The Discord for everyone, including trial users, can be accessed at the link below.
https://discord.gg/b6fwenZjez

**For Indie or Studio Users**
The link to the Discord for Indie or Studio users can be found in the purchase confirmation email.

Thank you for your understanding and cooperation.
