### ISSUE TITLE
Feedback for “Boolean”

### ISSUE THREAD

**Issue by luminahox** [shinjiesk/plasticity-unofficial-document#22]
Give an option under the preferences tab to invert the order of selection of bodies for boolean operations. This way, it would match better the way to make quick boolean operations in Blender, with the HardOps addon or the Bool Tool addon, where you get to select the active object last.

**Comment by shinjiesk** [comment]
We accept feature requests. Could you please submit your request here? We apologize for the inconvenience.
https://plasticity.canny.io/feature-requests
