### ISSUE TITLE
Found broken `/all-commands` link. Please fix!

### ISSUE THREAD

**Issue by PierrotTempo** [shinjiesk/plasticity-unofficial-document#30]
I was looking for a printable short cut list

**Comment by shinjiesk** [comment]
The structure of the site has changed, and you can find it on this page. 
https://doc.plasticity.xyz/all-commands/download-pdf

**Comment by shinjiesk** [comment]
Thank you for reaching out. We have addressed all the broken links you mentioned. Should you encounter any further issues with the links, please feel free to notify us again.
