### ISSUE TITLE
Customizing shortcuts

### ISSUE THREAD

**Issue by albertoMartinsen** [shinjiesk/plasticity-unofficial-document#38]
Is is possible to customize shortcuts/keybindings? I don't use an american keyboard (I use an European one) and some of the shorcuts like the new Dimension ( = ) one can't be used because I have press shift first and it doesn't work for me. I would love to have the possibility to edit them to make it easier for me (and many other people)

**Comment by shinjiesk** [comment]
Currently, there is no GUI available for key binding configuration. You can edit a JSON text file to change the key bindings. For detailed instructions, please refer to our official Discord support channel at https://discord.com/channels/893157887847845908/937291817056092240. 
Support for Plasticity is provided exclusively through Discord. We apologize for any inconvenience caused.
